#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# My environment variables.
export EDITOR='mvim'
export PAGER='less'
# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home
export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar
# Groovy
export GROOVY_HOME=/Users/siyuan/tools/groovy-2.3.4
# Maven
export M2_HOME=/Users/siyuan/tools/apache-maven
# Gradle
export GRADLE_HOME=/Users/siyuan/tools/gradle-2.0
# Tomcat
export CATALINA_HOME=/Users/siyuan/tools/apache-tomcat-6.0.41
export PATH=$PATH:$HOME/tools/bin:$JAVA_HOME/bin:$M2_HOME/bin:$CATALINA_HOME/bin:$GROOVY_HOME/bin:$GRADLE_HOME/bin


# 解决javac乱码
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
#export LC_ALL=C
#
export WORKING=/Users/siyuan/workspace/alibaba/cloudspace

