#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Environment variables.
# Java
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
export HADOOP_HOME=/usr/local/hadoop-2.7.2
export HADOOP_PREFIX=/usr/local/hadoop-2.7.2

export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar
# Groovy
export GROOVY_HOME=/Users/siyuan/tools/groovy-2.3.4
# Maven
export M2_HOME=/Users/siyuan/tools/apache-maven
# Gradle
export GRADLE_HOME=/Users/siyuan/tools/gradle-2.2.1
# Tomcat
export CATALINA_HOME=/Users/siyuan/tools/taobao-tomcat-7.0.52.1
# Sonar
export SONAR_RUNNER_HOME=/Users/siyuan/tools/sonar-runner-2.4

# Android Command Line Tools
export ANDROID_SDK_HOME=/Users/siyuan/Library/Android/sdk

export CUDA_HOME=/usr/local/cuda

#export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin:$M2_HOME/bin:$CATALINA_HOME/bin:$ANDROID_SDK_HOME/platform-tools:$HADOOP_HOME/bin
export PATH=$PATH:$CUDA_HOME/bin



# 解决javac乱码
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
#

export HISTTIMEFORMAT="%d%m%y %T "


